Create database Assessment;
use assessment;
select * from amazonsales;


-- 1. Display all unique product categories available in the dataset.
select  distinct Category from amazonsales; 

-- 2. Retrieve all orders that were cancelled.
select count(Status) as Status_Cancelled , Category from amazonsales
where Status = 'Cancelled'
group by Category;

-- 3. Find the top 10 most expensive orders (based on Amount)
select `Order ID` , Category , Amount as Expensive_Orders from amazonsales
order by Amount
Desc limit 10;

-- 4. Display all orders shipped to the state of Maharashtra.
select Status , `ship-state` , Category , `Order ID`from amazonsales
where Status = 'Shipped' and `ship-state` = "MAHARASHTRA";

-- 5. Show all orders where quantity is greater than 1.
select `Order ID`,Qty , Amount from amazonsales
where Qty > 1;

-- 6.Find the total revenue (SUM(Amount)) generated by all orders.
select round(sum(Amount)) from amazonsales;

-- 7.Count how many orders were successfully “Delivered to Buyer”.
select Count(Status) from amazonsales
where Status = 'Shipped - Delivered to Buyer';

-- 8.Find the number of orders for each category.
select  Category , count(`Order ID`) from amazonsales
group by Category; 

-- 9.Show the total number of orders placed each day.
select Date , count(`Order ID`) from amazonsales
group by Date;

-- 10.Find the average order amount per category.
select Category , round(avg(Amount)) from amazonsales
group by Category;

-- 11. Find the top 5 cities that generated the highest total revenue.
select `ship-city` , round(sum(Amount)) from amazonsales
group by `ship-city` 
order by sum(Amount) desc limit 5;

-- 12.Calculate the percentage of cancelled orders out of total orders.
select round(sum(case when Status like '%Cancelled%' then 1 else 0 end) *100.0/count(*),2)
as Cancelled_Order_pencentage from amazonsales;

-- 13.Identify which fulfilment method (“Amazon” or “Merchant”) made higher total revenue.
select Fulfilment , round(sum(Amount))  as Highest_revenue from amazonsales
group by Fulfilment 
order by sum(Amount) desc ;

-- 14.Find the most popular product size (based on number of orders).
select Size , count(`Order ID`) from amazonsales
group by Size
order by count(`Order ID`) desc 
limit 1;

-- 15. Display each state’s total revenue and the average order value(Qty).
select `ship-state` , round(sum(Amount),2) As Total_revenue , round(avg(Amount),2) As Average_Amount from amazonsales
group by `ship-state`;
